name: "Setup Go and Checkout Code"
description: "Checks out the code and sets up Go"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 20
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"
