version: '3'
services:
  redis:
    image: redis:7.4.1-alpine
    restart: always

    command: redis-server --save 20 1 --loglevel warning --port ${REDIS_PORT:-6379} --requirepass ${REDIS_PASSWORD:-''} # loaded and unexpended from .env but not pass to the container
    volumes: 
      - ./.cache:/data
    networks:
      - app-internal
  
  app:
    depends_on:
      - redis
    build: .
    env_file:
      - .env
    volumes:
      - ./:/go/src/github.com/LasramR/sclng-backend-test-lasramR
    
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    networks:
      - app-internal

    command: reflex -r '\.go$$' -s -- sh -c 'go build -buildvcs=false && ./sclng-backend-test-lasramR'
    stop_signal: SIGKILL

networks:
  app-internal:
    driver: bridge