version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/go/src/github.com/LasramR/sclng-backend-test-lasramR
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    command: reflex -r '\.go$$' -s -- sh -c 'go build -buildvcs=false && ./sclng-backend-test-lasramR'
    stop_signal: SIGKILL
