name: "Continuous Integration"

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        shell: bash
        run: |
          go install github.com/mfridman/tparse@latest
          go mod download
          go test -v ./... -cover -json | tparse -all -smallscreen
  
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build app
        shell: bash
        run: |
          go mod download
          go build -buildvcs=false